Fix "missing space before email" error.
Use a sed expression to delete empty author lines in the pipeline
between `bzr fast-export` and `git fast-import`.

If git imports a commit with malformed author field, then it will fail
to push the affected branch to any other remote like this:

	# git push origin
	error: object abc123: invalid author/committer line - missing space before email
	fatal: Error in object
	error: pack-objects died of signal 13

	# git fsck
	error in commit abc123: invalid author/committer line - missing space before email

These errors are caused by lines like this in the raw data:

	author <> 1234567890 +0000